package main

import (
	"time"
)

type Player struct {
	Assists                          int       `json:"assists"`
	Bonus                            int       `json:"bonus"`
	Bps                              int       `json:"bps"`
	ChanceOfPlayingNextRound         int       `json:"chance_of_playing_next_round"`
	ChanceOfPlayingThisRound         int       `json:"chance_of_playing_this_round"`
	CleanSheets                      int       `json:"clean_sheets"`
	CleanSheetsPer90                 float32   `json:"clean_sheets_per_90"`
	Code                             int       `json:"code"`
	CornersAndIndirectFreekicksOrder any       `json:"corners_and_indirect_freekicks_order"`
	CornersAndIndirectFreekicksText  string    `json:"corners_and_indirect_freekicks_text"`
	CostChangeEvent                  int       `json:"cost_change_event"`
	CostChangeEventFall              int       `json:"cost_change_event_fall"`
	CostChangeStart                  int       `json:"cost_change_start"`
	CostChangeStartFall              int       `json:"cost_change_start_fall"`
	Creativity                       string    `json:"creativity"`
	CreativityRank                   int       `json:"creativity_rank"`
	CreativityRankType               int       `json:"creativity_rank_type"`
	DirectFreekicksOrder             any       `json:"direct_freekicks_order"`
	DirectFreekicksText              string    `json:"direct_freekicks_text"`
	DreamteamCount                   int       `json:"dreamteam_count"`
	ElementType                      int       `json:"element_type"`
	EpNext                           string    `json:"ep_next"`
	EpThis                           string    `json:"ep_this"`
	EventPoints                      int       `json:"event_points"`
	ExpectedAssists                  string    `json:"expected_assists"`
	ExpectedAssistsPer90             float32   `json:"expected_assists_per_90"`
	ExpectedGoalInvolvements         string    `json:"expected_goal_involvements"`
	ExpectedGoalInvolvementsPer90    float32   `json:"expected_goal_involvements_per_90"`
	ExpectedGoals                    string    `json:"expected_goals"`
	ExpectedGoalsConceded            string    `json:"expected_goals_conceded"`
	ExpectedGoalsConcededPer90       float32   `json:"expected_goals_conceded_per_90"`
	ExpectedGoalsPer90               float32   `json:"expected_goals_per_90"`
	FirstName                        string    `json:"first_name"`
	Form                             string    `json:"form"`
	FormRank                         int       `json:"form_rank"`
	FormRankType                     int       `json:"form_rank_type"`
	GoalsConceded                    int       `json:"goals_conceded"`
	GoalsConcededPer90               float32   `json:"goals_conceded_per_90"`
	GoalsScored                      int       `json:"goals_scored"`
	IctIndex                         string    `json:"ict_index"`
	IctIndexRank                     int       `json:"ict_index_rank"`
	IctIndexRankType                 int       `json:"ict_index_rank_type"`
	ID                               int       `json:"id"`
	InDreamteam                      bool      `json:"in_dreamteam"`
	Influence                        string    `json:"influence"`
	InfluenceRank                    int       `json:"influence_rank"`
	InfluenceRankType                int       `json:"influence_rank_type"`
	Minutes                          int       `json:"minutes"`
	News                             string    `json:"news"`
	NewsAdded                        time.Time `json:"news_added"`
	NowCost                          int       `json:"now_cost"`
	NowCostRank                      int       `json:"now_cost_rank"`
	NowCostRankType                  int       `json:"now_cost_rank_type"`
	OwnGoals                         int       `json:"own_goals"`
	PenaltiesMissed                  int       `json:"penalties_missed"`
	PenaltiesOrder                   any       `json:"penalties_order"`
	PenaltiesSaved                   int       `json:"penalties_saved"`
	PenaltiesText                    string    `json:"penalties_text"`
	Photo                            string    `json:"photo"`
	PointsPerGame                    string    `json:"points_per_game"`
	PointsPerGameRank                int       `json:"points_per_game_rank"`
	PointsPerGameRankType            int       `json:"points_per_game_rank_type"`
	RedCards                         int       `json:"red_cards"`
	Saves                            int       `json:"saves"`
	SavesPer90                       float32   `json:"saves_per_90"`
	SecondName                       string    `json:"second_name"`
	SelectedByPercent                string    `json:"selected_by_percent"`
	SelectedRank                     int       `json:"selected_rank"`
	SelectedRankType                 int       `json:"selected_rank_type"`
	Special                          bool      `json:"special"`
	SquadNumber                      any       `json:"squad_number"`
	Starts                           int       `json:"starts"`
	StartsPer90                      float32   `json:"starts_per_90"`
	Status                           string    `json:"status"`
	Team                             int       `json:"team"`
	TeamCode                         int       `json:"team_code"`
	Threat                           string    `json:"threat"`
	ThreatRank                       int       `json:"threat_rank"`
	ThreatRankType                   int       `json:"threat_rank_type"`
	TotalPoints                      int       `json:"total_points"`
	TransfersIn                      int       `json:"transfers_in"`
	TransfersInEvent                 int       `json:"transfers_in_event"`
	TransfersOut                     int       `json:"transfers_out"`
	TransfersOutEvent                int       `json:"transfers_out_event"`
	ValueForm                        string    `json:"value_form"`
	ValueSeason                      string    `json:"value_season"`
	WebName                          string    `json:"web_name"`
	YellowCards                      int       `json:"yellow_cards"`
}
