-- Core FPL analytics schema.
-- Identity note: FPL element ids change every season; the stable cross-season
-- keys are the player `code` and team `code` fields from the FPL API.

create table if not exists seasons (
  id smallint generated by default as identity primary key,
  name text unique not null,            -- '2021-22'
  start_year smallint not null,
  is_current boolean not null default false
);

create table if not exists teams (
  code int primary key,
  name text not null,
  short_name text not null
);

create table if not exists team_seasons (
  season_id smallint not null references seasons(id),
  team_code int not null references teams(code),
  fpl_team_id smallint not null,        -- 1..20 within that season
  strength_overall_home smallint,
  strength_overall_away smallint,
  strength_attack_home smallint,
  strength_attack_away smallint,
  strength_defence_home smallint,
  strength_defence_away smallint,
  primary key (season_id, team_code),
  unique (season_id, fpl_team_id)
);

create table if not exists players (
  code int primary key,
  first_name text,
  second_name text,
  web_name text
);

create table if not exists player_seasons (
  season_id smallint not null references seasons(id),
  player_code int not null references players(code),
  fpl_element_id int not null,
  position smallint not null,           -- 1 GK, 2 DEF, 3 MID, 4 FWD
  team_code int references teams(code),
  now_cost smallint,                    -- price in 0.1m units
  status text,                          -- a/i/d/s/u
  chance_of_playing smallint,
  primary key (season_id, player_code),
  unique (season_id, fpl_element_id)
);

create table if not exists fixtures (
  season_id smallint not null references seasons(id),
  fpl_fixture_id int not null,
  gameweek smallint,                    -- null until scheduled
  kickoff_time timestamptz,
  home_team_code int references teams(code),
  away_team_code int references teams(code),
  home_difficulty smallint,
  away_difficulty smallint,
  home_score smallint,
  away_score smallint,
  finished boolean not null default false,
  primary key (season_id, fpl_fixture_id)
);

create table if not exists player_gameweeks (
  season_id smallint not null references seasons(id),
  player_code int not null references players(code),
  gameweek smallint not null,
  fpl_fixture_id int not null default 0,  -- 0 when fixture unknown; two rows per GW on DGWs
  opponent_team_code int,
  was_home boolean,
  minutes smallint,
  total_points smallint,
  goals_scored smallint,
  assists smallint,
  clean_sheets smallint,
  goals_conceded smallint,
  saves smallint,
  bonus smallint,
  bps smallint,
  yellow_cards smallint,
  red_cards smallint,
  own_goals smallint,
  penalties_saved smallint,
  penalties_missed smallint,
  influence numeric,
  creativity numeric,
  threat numeric,
  ict_index numeric,
  expected_goals numeric,               -- null before 2022-23
  expected_assists numeric,
  expected_goal_involvements numeric,
  expected_goals_conceded numeric,
  value smallint,                       -- price at that GW, 0.1m units
  selected_by int,
  transfers_in int,
  transfers_out int,
  primary key (season_id, player_code, gameweek, fpl_fixture_id)
);
create index if not exists idx_pgw_season_gw on player_gameweeks (season_id, gameweek);
create index if not exists idx_pgw_player on player_gameweeks (player_code);

create table if not exists predictions (
  season_id smallint not null references seasons(id),
  player_code int not null references players(code),
  gameweek smallint not null,
  predicted_points numeric not null,
  predicted_minutes numeric,
  rating text,                          -- excellent / good / average / poor
  model_version text not null,
  created_at timestamptz not null default now(),
  primary key (season_id, player_code, gameweek, model_version)
);

-- Backend connects with service credentials which bypass RLS; enabling RLS
-- with no anon policies keeps the tables closed to the public API surface.
alter table seasons enable row level security;
alter table teams enable row level security;
alter table team_seasons enable row level security;
alter table players enable row level security;
alter table player_seasons enable row level security;
alter table fixtures enable row level security;
alter table player_gameweeks enable row level security;
alter table predictions enable row level security;
